version: '3.8'
services:
  backend:
    build: ./backend/
    tty: true
    volumes:
      - data:/data
    environment:
      - PORT=8000
    ports: 
      - 8000:8000

  frontend:
    build: ./frontend/
    depends_on:
      - backend
    ports:
      - 3000:3000

volumes:
  data: